### ISSUE TITLE
Please give me write access to this repository

### ISSUE THREAD

**Issue by crontab** [cwengmusiclife/firmware#1]
Hi Chi-Cheong,

Hovik Melikyan here from AllDSP. I don't think I can upload files here without forking the repository. I think it would be best if you gave me full access rights here.

Thanks!

**Comment by cwengmusiclife** [comment]
Hey Just added you as a collaborator. :-) Check if you have full acces now.
Thanks!

**Comment by cwengmusiclife** [comment]
Jeroen,

What's your github id? Let me add you as a collaborator to the firmware
repository also.

Chi-Cheong

**Comment by cwengmusiclife** [comment]
Hi Hovik,

I see that you've just uploaded the exe file. That's for upgrading from a
PC. It's not practical to manually upgrade Bulls after they've been
assembled.

So could you also upload the file that can be directly burned to the PCB
for bull?

Chi-Cheong
